server:
  port: 7001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/elevens-bank
    username: shrikar
    password: Mukesh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
