server:
  port: 7001

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  server:
    port: 8086

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/elevens-bank
    username: shrikar
    password: Mukesh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
